// Generated by gencpp from file vel_test/CheckValidResponse.msg
// DO NOT EDIT!


#ifndef VEL_TEST_MESSAGE_CHECKVALIDRESPONSE_H
#define VEL_TEST_MESSAGE_CHECKVALIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vel_test
{
template <class ContainerAllocator>
struct CheckValidResponse_
{
  typedef CheckValidResponse_<ContainerAllocator> Type;

  CheckValidResponse_()
    : status(0)  {
    }
  CheckValidResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::vel_test::CheckValidResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vel_test::CheckValidResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckValidResponse_

typedef ::vel_test::CheckValidResponse_<std::allocator<void> > CheckValidResponse;

typedef boost::shared_ptr< ::vel_test::CheckValidResponse > CheckValidResponsePtr;
typedef boost::shared_ptr< ::vel_test::CheckValidResponse const> CheckValidResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vel_test::CheckValidResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vel_test::CheckValidResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vel_test::CheckValidResponse_<ContainerAllocator1> & lhs, const ::vel_test::CheckValidResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vel_test::CheckValidResponse_<ContainerAllocator1> & lhs, const ::vel_test::CheckValidResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vel_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vel_test::CheckValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vel_test::CheckValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vel_test::CheckValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vel_test::CheckValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_test::CheckValidResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_test::CheckValidResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vel_test::CheckValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::vel_test::CheckValidResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::vel_test::CheckValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vel_test/CheckValidResponse";
  }

  static const char* value(const ::vel_test::CheckValidResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vel_test::CheckValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
;
  }

  static const char* value(const ::vel_test::CheckValidResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vel_test::CheckValidResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckValidResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vel_test::CheckValidResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vel_test::CheckValidResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEL_TEST_MESSAGE_CHECKVALIDRESPONSE_H
