// Generated by gencpp from file vel_test/CheckValid.msg
// DO NOT EDIT!


#ifndef VEL_TEST_MESSAGE_CHECKVALID_H
#define VEL_TEST_MESSAGE_CHECKVALID_H

#include <ros/service_traits.h>


#include <vel_test/CheckValidRequest.h>
#include <vel_test/CheckValidResponse.h>


namespace vel_test
{

struct CheckValid
{

typedef CheckValidRequest Request;
typedef CheckValidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckValid
} // namespace vel_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vel_test::CheckValid > {
  static const char* value()
  {
    return "ffe373b808a90218f6a495ef5089335a";
  }

  static const char* value(const ::vel_test::CheckValid&) { return value(); }
};

template<>
struct DataType< ::vel_test::CheckValid > {
  static const char* value()
  {
    return "vel_test/CheckValid";
  }

  static const char* value(const ::vel_test::CheckValid&) { return value(); }
};


// service_traits::MD5Sum< ::vel_test::CheckValidRequest> should match
// service_traits::MD5Sum< ::vel_test::CheckValid >
template<>
struct MD5Sum< ::vel_test::CheckValidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vel_test::CheckValid >::value();
  }
  static const char* value(const ::vel_test::CheckValidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vel_test::CheckValidRequest> should match
// service_traits::DataType< ::vel_test::CheckValid >
template<>
struct DataType< ::vel_test::CheckValidRequest>
{
  static const char* value()
  {
    return DataType< ::vel_test::CheckValid >::value();
  }
  static const char* value(const ::vel_test::CheckValidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vel_test::CheckValidResponse> should match
// service_traits::MD5Sum< ::vel_test::CheckValid >
template<>
struct MD5Sum< ::vel_test::CheckValidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vel_test::CheckValid >::value();
  }
  static const char* value(const ::vel_test::CheckValidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vel_test::CheckValidResponse> should match
// service_traits::DataType< ::vel_test::CheckValid >
template<>
struct DataType< ::vel_test::CheckValidResponse>
{
  static const char* value()
  {
    return DataType< ::vel_test::CheckValid >::value();
  }
  static const char* value(const ::vel_test::CheckValidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEL_TEST_MESSAGE_CHECKVALID_H
