// Generated by gencpp from file vel_test/CheckValidRequest.msg
// DO NOT EDIT!


#ifndef VEL_TEST_MESSAGE_CHECKVALIDREQUEST_H
#define VEL_TEST_MESSAGE_CHECKVALIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vel_test
{
template <class ContainerAllocator>
struct CheckValidRequest_
{
  typedef CheckValidRequest_<ContainerAllocator> Type;

  CheckValidRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  CheckValidRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::vel_test::CheckValidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vel_test::CheckValidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckValidRequest_

typedef ::vel_test::CheckValidRequest_<std::allocator<void> > CheckValidRequest;

typedef boost::shared_ptr< ::vel_test::CheckValidRequest > CheckValidRequestPtr;
typedef boost::shared_ptr< ::vel_test::CheckValidRequest const> CheckValidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vel_test::CheckValidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vel_test::CheckValidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vel_test::CheckValidRequest_<ContainerAllocator1> & lhs, const ::vel_test::CheckValidRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vel_test::CheckValidRequest_<ContainerAllocator1> & lhs, const ::vel_test::CheckValidRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vel_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vel_test::CheckValidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vel_test::CheckValidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vel_test::CheckValidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vel_test::CheckValidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_test::CheckValidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vel_test::CheckValidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vel_test::CheckValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::vel_test::CheckValidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vel_test::CheckValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vel_test/CheckValidRequest";
  }

  static const char* value(const ::vel_test::CheckValidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vel_test::CheckValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::vel_test::CheckValidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vel_test::CheckValidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckValidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vel_test::CheckValidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vel_test::CheckValidRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEL_TEST_MESSAGE_CHECKVALIDREQUEST_H
